checkstyle-all/pom.xml, sonar-checkstyle-plugin/pom.xml, sonar-checkstyle-plugin/src/main/resources/org/sonar/l10n/checkstyle.properties, sonar-checkstyle-plugin/src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle/com.puppycrawl.tools.checkstyle.checks.TranslationCheck.html, sonar-checkstyle-plugin/src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle/com.puppycrawl.tools.checkstyle.checks.naming.CatchParameterNameCheck.html, sonar-checkstyle-plugin/src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle/com.puppycrawl.tools.checkstyle.checks.regexp.RegexpOnFilenameCheck.html, sonar-checkstyle-plugin/src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle/com.puppycrawl.tools.checkstyle.checks.whitespace.SingleSpaceSeparatorCheck.html
Add missing translations for 7.1.
Also update the parent version of the submodule POMs.
=> Add missing 7.1 translations

checkstyle-all/pom.xml, sonar-checkstyle-plugin/pom.xml, sonar-checkstyle-plugin/src/main/resources/com/sonar/sqale/checkstyle-model.xml, sonar-checkstyle-plugin/src/main/resources/org/sonar/l10n/checkstyle.properties, sonar-checkstyle-plugin/src/test/java/org/sonar/plugins/checkstyle/CheckstyleRulesDefinitionTest.java
This commit contains a couple of changes that fix the master branch
build:
- Add Sqale configurations for new rules where it makes sense. I'm not
familiar with Sqale and had to guess.
- Set a classifier for the shaded artifact and use that. This makes
sure the relocated Guava version is used for Checkstyle and the
not-relocated one for Sonar.
- Incremented the expected rule count.
- Add more mission translations.
I did not yet test a SNAPSHOT build against Sonar.
=> Fix master branch build

checkstyle-sonar-plugin/pom.xml, checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/internal/CheckUtil.java, checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/internal/ChecksTest.java
Issue #28
Ant dependency is because classpath search was throwing class not found exception without it. I assume it is because we have ant classes in checkstyle main code.
Test is fixed, updated with new code from checkstyle.
Test was tweaked to skip filters. I am leaving fileset checks in until we can ascertain if they should be in or not.
=> Issue #28: fix broken rules test

checkstyle-sonar-plugin/src/main/java/org/sonar/plugins/checkstyle/CheckstyleConfiguration.java, checkstyle-sonar-plugin/src/main/java/org/sonar/plugins/checkstyle/CheckstyleExecutor.java, checkstyle-sonar-plugin/src/main/java/org/sonar/plugins/checkstyle/CheckstylePlugin.java, checkstyle-sonar-plugin/src/main/java/org/sonar/plugins/checkstyle/CheckstyleProfileExporter.java, checkstyle-sonar-plugin/src/main/java/org/sonar/plugins/checkstyle/CheckstyleProfileImporter.java, checkstyle-sonar-plugin/src/main/java/org/sonar/plugins/checkstyle/CheckstyleSensor.java, checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/CheckstyleExecutorTest.java, checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/internal/ChecksTest.java
The plugin currently depends on Guava. For checkstyle itself this is
not an issue but for the plugin it has negative consequences. Before
SonarQube 5.2 this meant that the version of Guava the plugin uses and
the one that SonarQube uses had to match. This can be a challenge
because the Google versioning policy is rather opionated. In SonarQube
5.2 and later sonar-packaging-maven-plugin stubbornly refuses to
package Guava because it is not aware of the class loading changes in
5.2 and assumes Guava is still provided by SonarQube when in fact it's
not.
With these changes the only Guava dependencies left in the source of
the plugin are VisibleForTesting. As this is only an annotation for
documentation purposes it is inconsequential if it can't be loaded at
runtime.
The tests still depend on …
=> Lessen dependency on Guava

checkstyle-sonar-plugin/config/sevntu_suppressions.xml, checkstyle-sonar-plugin/config/suppressions.xml, checkstyle-sonar-plugin/src/main/java/org/sonar/plugins/checkstyle/CheckstyleAuditListener.java, checkstyle-sonar-plugin/src/main/java/org/sonar/plugins/checkstyle/CheckstyleConfiguration.java, checkstyle-sonar-plugin/src/main/java/org/sonar/plugins/checkstyle/CheckstyleExecutor.java, checkstyle-sonar-plugin/src/main/java/org/sonar/plugins/checkstyle/CheckstyleProfileExporter.java, checkstyle-sonar-plugin/src/main/java/org/sonar/plugins/checkstyle/CheckstyleProfileImporter.java, checkstyle-sonar-plugin/src/main/java/org/sonar/plugins/checkstyle/CheckstyleRulesDefinition.java, checkstyle-sonar-plugin/src/main/java/org/sonar/plugins/checkstyle/CheckstyleSensor.java, checkstyle-sonar-plugin/src/main/java/org/sonar/plugins/checkstyle/CheckstyleSeverityUtils.java, checkstyle-sonar-plugin/src/main/java/org/sonar/plugins/checkstyle/CheckstyleVersion.java, checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/CheckstyleAuditListenerTest.java, checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/CheckstyleConfigurationTest.java, checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/CheckstyleConstantsTest.java, checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/CheckstyleExecutorTest.java, checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/CheckstylePluginTest.java, checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/CheckstyleProfileExporterTest.java, checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/CheckstyleProfileImporterTest.java, checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/CheckstyleRulesDefinitionTest.java, checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/CheckstyleSensorTest.java, checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/CheckstyleSeverityUtilsTest.java, checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/CheckstyleTestUtils.java, checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/internal/ChecksTest.java
=> Issue #45: resolved many checkstyle violations

checkstyle-sonar-plugin/config/intellij-idea-inspections.xml, checkstyle-sonar-plugin/config/pmd-main.xml, checkstyle-sonar-plugin/config/pmd-test.xml, checkstyle-sonar-plugin/config/pmd.xml, checkstyle-sonar-plugin/pom.xml, checkstyle-sonar-plugin/src/main/java/org/sonar/plugins/checkstyle/CheckstyleExecutor.java, checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/CheckstyleProfileImporterTest.java, checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/internal/ChecksTest.java
=> Issue #160: fix teamcity violations

checkstyle-sonar-plugin/config/Dockerfile
Docker image update to 7.3 but based on alpine.
The reason is that SonarQube officially stopped distributing Docker images due to the different versions. Then, the latest official repository version of the alpine version has been forked and continued with the latest SonarQube versions starting with 7.3.
=> update sonarqube docker image

wercker.yml
build problem found at https://app.wercker.com/checkstyle/sonar-checkstyle/runs/build/5c2286e9c0c3d700119431f0?step=5c2286e9c0c3d700119431f5
caused by my latest changes in docker repo to assist #157 
https://hub.docker.com/r/checkstyle/sonarqube-maven-git/tags
=> minor: make wercker use strict version of docker image to make CI stable

README.md, pom.xml, src/main/resources/com/sonar/sqale/checkstyle-model.xml, src/main/resources/org/sonar/l10n/checkstyle.properties, src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle/com.puppycrawl.tools.checkstyle.checks.javadoc.MissingJavadocTypeCheck.html, src/main/resources/org/sonar/plugins/checkstyle/rules.xml, src/test/java/org/sonar/plugins/checkstyle/CheckstyleRulesDefinitionTest.java
Fixes #213.
Please adapt CI first after the merge of #214 to have a clean CI run for this PR.
=> Issue #213: update to CS 8.20

src/main/java/org/sonar/plugins/checkstyle/package-info.java
add javadoc to package-info
from https://github.com/checkstyle/checkstyle/pull/6798#pullrequestreview-249707120
=> minor: add javadoc to package-info

pom.xml
Issue #234 
- `sevntu-checkstyle-maven-plugin` was replaced with `sevntu-checks dependency`
- `sevntu-checks` bumped to 1.35.0
The two commits are not related to each other, so I split them.
=> Issue #234: replace sevntu-checkstyle-maven-plugin with sevntu-checks

pom.xml, src/main/resources/com/sonar/sqale/checkstyle-model.xml, src/main/resources/org/sonar/l10n/checkstyle.properties, src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle/com.puppycrawl.tools.checkstyle.checks.annotation.MissingDeprecatedCheck.html, src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle/com.puppycrawl.tools.checkstyle.checks.coding.UnnecessarySemicolonAfterTypeMemberDeclarationCheck.html, src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle/com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocBlockTagLocationCheck.html, src/main/resources/org/sonar/plugins/checkstyle/rules.xml, src/test/java/org/sonar/plugins/checkstyle/CheckstyleProfileExporterTest.java, src/test/java/org/sonar/plugins/checkstyle/CheckstyleRulesDefinitionTest.java, src/test/resources/org/sonar/plugins/checkstyle/CheckstyleProfileExporterTest/singleCheckstyleRulesToExport.xml
fixes #240 
line length and missing deprecated checks before update:
after update they are still working without exception. after recreation of them they work the same:
javadoc block:
unnecessary semicolon:
however, i was not able to verify the filters:
can you please check them for the `idFormat` property?
=> Issue #240: update to CS 8.24

README.md, pom.xml, src/main/java/org/sonar/plugins/checkstyle/CheckstyleExecutor.java, src/main/resources/org/sonar/l10n/checkstyle.properties, src/main/resources/org/sonar/plugins/checkstyle/rules.xml
fixes #244 
regexpmultiline check:
results:
=> Issue #244: update to CS 8.25

README.md, pom.xml, src/main/resources/com/sonar/sqale/checkstyle-model.xml, src/main/resources/org/sonar/l10n/checkstyle.properties, src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle/com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocContentLocationCheck.html, src/main/resources/org/sonar/plugins/checkstyle/rules.xml, src/test/java/org/sonar/plugins/checkstyle/CheckstyleRulesDefinitionTest.java
fix #253 
I have got a problem here as the new check doesn't seem to work.
My example Java class is:
```
/** This comment causes a violation because it starts from the first line
* and spans several lines.
*/
/**
* This comment is OK because it starts from the second line.
*/
/** This comment is OK because it is on the single line. */
public class App {
/** This comment causes a violation because it starts from the first line
* and spans several lines.
*/
/**
* This comment is OK because it starts from the second line.
*/
/** This comment is OK because it is on the single line. */
public String getGreeting() {
return "Hello world.";
}
/** This comment causes a violation because it starts from the first line
* and spans several lines.
*/
/**
* This comment is OK because it starts from the …
```
=> Issue #253: update to CS 8.27

.ci/wercker.sh, pom.xml
In order to be able to send JaCoCo reports to Sonarqube, we have to:
- run unit tests instrumented with JaCoCo
- setup Sonar integration correctly
=> #270: send jacoco coverage to sonarqube

src/it/java/org/checkstyle/plugins/sonar/CheckJarTest.java, src/it/java/org/checkstyle/plugins/sonar/RunPluginTest.java, src/test/java/org/sonar/plugins/checkstyle/internal/ChecksTest.java
enables checkstyle for test sources as it was disabled by default.
i face one problem in `ChecksTest::getFinalProperties` (L400) with the lambda expression again:
- checkstyle demands braces, IDEA inspections don't
- not adding a line break here will result in a line being > 100 characters -> checkstyle fails
@romani please take a look
=> #269: Enable CS for test sources

pom.xml, src/test/java/org/sonar/plugins/checkstyle/internal/ChecksTest.java
fix #269 
updates the `pom.xml` to include test sources in checkstyle analysis.
see #272
=> #269: update pom.xml

README.md, pom.xml, src/it/java/org/checkstyle/plugins/sonar/CheckJarTest.java, src/main/resources/com/sonar/sqale/checkstyle-model.xml, src/main/resources/org/sonar/l10n/checkstyle.properties, src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle/com.puppycrawl.tools.checkstyle.checks.coding.AvoidNoArgumentSuperConstructorCallCheck.html, src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle/com.puppycrawl.tools.checkstyle.checks.coding.FallThroughCheck.html, src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle/com.puppycrawl.tools.checkstyle.checks.coding.NoEnumTrailingCommaCheck.html, src/main/resources/org/sonar/plugins/checkstyle/rules.xml, src/test/java/org/sonar/plugins/checkstyle/CheckstyleRulesDefinitionTest.java
fix #281 
new checks working fine:
=> Issue #281: update to CS 8.29

README.md, pom.xml, src/it/java/org/checkstyle/plugins/sonar/CheckJarTest.java, src/main/resources/com/sonar/sqale/checkstyle-model.xml, src/main/resources/org/sonar/l10n/checkstyle.properties, src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle/com.puppycrawl.tools.checkstyle.checks.coding.AvoidDoubleBraceInitializationCheck.html, src/main/resources/org/sonar/plugins/checkstyle/rules.xml, src/test/java/org/sonar/plugins/checkstyle/CheckstyleRulesDefinitionTest.java
fix #286
Furthermore, there are some errors in the documentation at https://checkstyle.sourceforge.io/config_coding.html#AvoidDoubleBraceInitialization.
Each `new ArrayList<Object>` i smissing braces: `new ArrayList<Object>()` will be correct.
Sonarqube:
=> Issue #286: update CS 8.30

src/main/resources/org/sonar/plugins/checkstyle/rules.xml
fix #298 
SQ does not show any errors after updating.
Before:
After:
=> Issue #298: fix AnnotationLocationCheck

.ci/travis.sh, pom.xml, src/main/java/org/sonar/plugins/checkstyle/metadata/CheckstyleMetadata.java, src/test/java/org/sonar/plugins/checkstyle/CheckstyleRulesDefinitionTest.java, src/test/java/org/sonar/plugins/checkstyle/internal/ChecksTest.java, src/test/java/org/sonar/plugins/checkstyle/metadata/CheckstyleMetadataTest.java
#317
- New check `RecordComponentNumberCheck` (to be released in `8.36`) metadata is successfully loaded from checkstyle, without manual entry in `rules.xml`
- The number of checks has also increased to `178` from `174`.
=> Issue #317: New metadata maintanence method: Fetch directly from checketyle

src/main/java/org/sonar/plugins/checkstyle/metadata/CheckstyleMetadata.java
#322 
`Boolean`
`Integer`
NB: There is no regex type in sonar. 
```
public final class RuleParamType {
private static final String OPTION_SEPARATOR = ",";
public static final RuleParamType STRING = new RuleParamType("STRING", new String[0]);
public static final RuleParamType TEXT = new RuleParamType("TEXT", new String[0]);
public static final RuleParamType BOOLEAN = new RuleParamType("BOOLEAN", new String[0]);
public static final RuleParamType INTEGER = new RuleParamType("INTEGER", new String[0]);
public static final RuleParamType FLOAT = new RuleParamType("FLOAT", new String[0]);
private static final String CSV_SPLIT_REGEX = ",(?=([^\"]*\"[^\"]*\")*[^\"]*$)";
```
=> Issue 322: fix type input validation - caused from 8.36 update onwards

src/main/java/org/sonar/plugins/checkstyle/metadata/CheckstyleMetadata.java
#328
`lowerCase`
`upperCase`
`accetable values list`
=> Issue #328: Allow lower case enum values in check config

README.md, pom.xml, src/main/resources/org/sonar/l10n/checkstyle.properties, src/main/resources/org/sonar/plugins/checkstyle/rules.xml, src/test/java/org/sonar/plugins/checkstyle/CheckstyleRulesDefinitionTest.java
fix #353.
New check:
DesignForExtension new property (default value):
=> Issue #353: update to CS 8.40

.github/workflows/sonar-checkstyle-workflows.yml
After discussion with @rnveach , we have decided to move travis CI tasks to github workflows. I have left `travis.yml` in place for now; I am not sure if we should delete it or just disable travis on this repo (or both).
Edit: Travis is currently not running
=> infra: move all travis jobs to GitHub workflows

.github/workflows/sonar-checkstyle-workflows.yml, .gitignore, README.md, pom.xml, src/it/java/org/checkstyle/plugins/sonar/RunPluginTest.java, src/test/java/org/sonar/plugins/checkstyle/CheckstyleConstantsTest.java, src/test/java/org/sonar/plugins/checkstyle/CheckstyleSeverityUtilsTest.java
- fixes #403
- drops java 1.8 support in accordance with checkstyle 10.0
Whitespace After check:
=> Issue #403: upgrade to checkstyle 10.0; drop java 1.8 support

pom.xml, src/main/java/org/sonar/plugins/checkstyle/CheckstyleSensor.java, src/test/java/org/sonar/plugins/checkstyle/CheckstyleSensorTest.java
Issue #40
Removed the dependency.
I was not seeing any classpath shenanigans mentioned in the issue unless its happening via reflection or such.
The code before this was causing issues with Eclipse:
> The package javax.xml.stream is accessible from more than one module: <unnamed>, java.xml	CheckstyleProfileImporter.java	/sonar-checkstyle/src/main/java/org/sonar/plugins/checkstyle	line 28	Java Problem
https://stackoverflow.com/questions/55571046/eclipse-is-confused-by-imports-accessible-from-more-than-one-module
=> Issue #40: removed sonar-java-plugin

.circleci/config.yml
Identified at https://github.com/checkstyle/sonar-checkstyle/pull/433#issuecomment-1281704317
=> infra: fix build and plugin execution

pom.xml
Upgrades jackson.dataformat to avoid some vulnerabilites in org.yaml:snakeyaml . This upgrades snakeyaml to 1.33 (from 1.27). 1.31 and 1.32 is the reported vulnerable versions.
This dependency is used in [CheckstyleMetadata](https://github.com/checkstyle/sonar-checkstyle/blob/f7f93d4db2d2c905daf2f05280a92a7248a71429/src/main/java/org/sonar/plugins/checkstyle/metadata/CheckstyleMetadata.java#L49) .
https://app.snyk.io/org/checkstyle/project/c790296d-5e05-4755-b64c-85724020c357?utm_campaign=vuln_alert&utm_medium=email&utm_source=Project&fromGitHubAuth=true
=> dependency: upgrade jackson.dataformat to 2.14.0

config/suppressions.xml, src/main/java/org/sonar/plugins/checkstyle/CheckstyleExecutor.java, src/main/java/org/sonar/plugins/checkstyle/metadata/CheckstyleMetadata.java, src/main/java/org/sonar/plugins/checkstyle/rule/ActiveRuleWrapper.java
Makes the list more manageable.
=> minor: splits up javadoc suppressions

.github/workflows/bump-license-year.yml
Signed-off-by: jongwooo <jongwooo.han@gmail.com>
Resolve  #467 
Update `bump-license-year.yml` to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow files that use `set-output` command through the following command:
```bash
$ find .github/workflows -name '*.yml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yml
run: |
echo "::set-output name=year::$(date +'%Y')"
```
**TO-BE**
```yml
run: |
echo "year=$(date +'%Y')" >> $GITHUB_OUTPUT
```
=> Issue #467: Replace deprecated command with environment file

README.md, pom.xml
fixes #455 
N.B.: sevntu and checkstyle config locations have been mixed up; corrected both lines
javadoc style check:
=> Issue #455: upgrade to checkstyle 10.6.0

config/pmd.xml, config/spotbugs-exclude.xml, pom.xml, src/main/java/org/sonar/plugins/checkstyle/metadata/CheckUtil.java, src/main/java/org/sonar/plugins/checkstyle/metadata/CheckstyleMetadata.java, src/main/java/org/sonar/plugins/checkstyle/metadata/ModuleFactory.java
Issue #465
I did a no harm test by having a test run `new CheckstyleMetadata(repository).createRulesWithMetadata();`. It loaded 40 checks with no issues.
=> Issue #465: adds caching for metadata around PackageObjectFactory

src/main/java/org/sonar/plugins/checkstyle/CheckstyleProfileImporter.java, src/test/java/org/sonar/plugins/checkstyle/CheckstyleProfileExporterTest.java, src/test/java/org/sonar/plugins/checkstyle/CheckstyleProfileImporterTest.java
minor: make private class final with default constructor
This is part of https://github.com/checkstyle/checkstyle/pull/12737
According to the https://docs.oracle.com/javase/specs/jls/se17/html/jls-8.html#jls-8.8.9 The default constructor has the same access modifier as the class. 
and  according to the check https://checkstyle.org/config_design.html#FinalClass  a class that has only private constructors and has no descendant classes is declared as final.
=> [WIP] minor: make private class final with default constructor

README.md
This refers to an event 8 years in the past and is more confusing than helpful.
=> minor: Remove project transfer note from readme

pom.xml
Use the release property instead of source and target for compilation.
=> infra: avoid maven warnings
