checkstyle/sonar-checkstyle

- sonar-checkstyle-plugin/pom.xml
Increase the file size limit checked by the enforcer plugin.
> Increase the file size limit

- checkstyle-sonar-plugin/src/main/java/org/sonar/plugins/checkstyle/CheckstyleProfileImporter.java
- checkstyle-sonar-plugin/src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle/com.puppycrawl.tools.checkstyle.checks.coding.EqualsAvoidNullCheck.html
- checkstyle-sonar-plugin/src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle/com.puppycrawl.tools.checkstyle.checks.coding.NoCloneCheck.html
- checkstyle-sonar-plugin/src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle/com.puppycrawl.tools.checkstyle.checks.header.HeaderCheck.html
- checkstyle-sonar-plugin/src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle/com.puppycrawl.tools.checkstyle.checks.header.RegexpHeaderCheck.html
- checkstyle-sonar-plugin/src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle/com.puppycrawl.tools.checkstyle.checks.imports.ImportControlCheck.html
- checkstyle-sonar-plugin/src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle/com.puppycrawl.tools.checkstyle.checks.whitespace.FileTabCharacterCheck.html
- checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/CheckstyleAuditListenerTest.java
- checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/CheckstyleConfigurationTest.java
- checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/CheckstyleExecutorTest.java
- checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/CheckstyleSensorTest.java
- checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/CheckstyleTestUtils.java
- checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/internal/CheckUtil.java
- checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/internal/ChecksTest.java
Issue #49 . Fix various rule violations reported by Teamcity.
> Issue #49: Reduce rule violations

- checkstyle-sonar-plugin/src/main/java/org/sonar/plugins/checkstyle/CheckstyleExecutor.java
- checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/CheckstyleExecutorTest.java
This commit fixes Issue: #71 by removing a redundant null check
> Issue #71: fix violation at sonarqube.com

- checkstyle-sonar-plugin/config/suppressions.xml
- checkstyle-sonar-plugin/src/main/resources/org/sonar/l10n/checkstyle.properties
- checkstyle-sonar-plugin/src/main/resources/org/sonar/plugins/checkstyle/rules.xml
- checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/internal/CheckUtil.java
- checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/internal/ChecksTest.java
Issue #28
We only validate tokens. We can't validate all properties, like in main checkstyle repo.
This should fix the direct issue in #75 with the parameter type field.
> Issue #28: added validation tokens for all modules

- checkstyle-sonar-plugin/config/pmd.xml
- checkstyle-sonar-plugin/src/main/resources/org/sonar/l10n/checkstyle.properties
- checkstyle-sonar-plugin/src/main/resources/org/sonar/plugins/checkstyle/rules.xml
- checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/internal/ChecksTest.java
Issue #94 
Added override for 2 checks.
> Issue #94: added support for tabWidth in specific checks

- pom.xml
> Issue #86: api is upgraded to 5.6.6

- checkstyle-sonar-plugin/src/main/resources/org/sonar/plugins/checkstyle/rules.xml
> Issue #103: fix ParameterName accessModifiers default value

- checkstyle-sonar-plugin/src/main/resources/org/sonar/plugins/checkstyle/rules.xml
> Issue #105: add ParameterNumber max default value

- checkstyle-sonar-plugin/src/main/resources/org/sonar/l10n/checkstyle.properties
- checkstyle-sonar-plugin/src/main/resources/org/sonar/plugins/checkstyle/rules.xml
- pom.xml
> Issue #100: upgraded checkstyle to 7.7

- checkstyle-sonar-plugin/src/main/resources/org/sonar/plugins/checkstyle/rules.xml
- checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/internal/ChecksTest.java
> Issue #114: fix javadocTokens values for NonEmptyAtclauseDescriptionCheck

- checkstyle-sonar-plugin/config/intellij-idea-inspections.xml
#49 .
base on https://youtrack.jetbrains.com/issue/IDEA-138401
configuration of TC was updated to make build of all jars before IDEA is launched
> Test for idea suppressions

- checkstyle-sonar-plugin/src/main/resources/org/sonar/plugins/checkstyle/rules.xml
Issue #145 change to support multiple instances. Not sure what would happen if people already have this rule configured in a singular manner.
> Issue #145: Templatise the Separator Wrap rule 

- checkstyle-sonar-plugin/config/intellij-idea-inspections.xml
no changes, just import and export.
> config: import old inspection file and export it by Idea 2018.3.1, no extra changes

- pom.xml
Issue #163 
testing is provided in issue comment.
> Issue #163: update to use checkstyle 8.13

- checkstyle-sonar-plugin/src/main/resources/org/sonar/plugins/checkstyle/rules.xml
- pom.xml
> Issue #163: update to checkstyle 8.14

- checkstyle-sonar-plugin/config/intellij-idea-inspections.xml
EqualsBetwenInconvertibleTypes till issue is resolved"
This reverts commit 4985a4056b855a21b6abac6496114e59853d2093.
This PR is result of conversation at https://teamcity-support.jetbrains.com/hc/en-us/requests/1917797
WIP.
> WIP - Revert "Issue #176: disable UnusedImport RedundantThrows 

- README.md
- checkstyle-sonar-plugin/src/main/resources/com/sonar/sqale/checkstyle-model.xml
- checkstyle-sonar-plugin/src/main/resources/org/sonar/l10n/checkstyle.properties
- checkstyle-sonar-plugin/src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle/com.puppycrawl.tools.checkstyle.checks.modifier.ClassMemberImpliedModifierCheck.html
- checkstyle-sonar-plugin/src/main/resources/org/sonar/plugins/checkstyle/rules.xml
- checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/CheckstyleRulesDefinitionTest.java
- pom.xml
> Issue #180: upgrade to checkstyle 8.16

- .circleci/config.yml
> Issue #175: wrap grep with test to pass pipefail of wercker

- .circleci/config.yml
- checkstyle-sonar-plugin/config/Dockerfile
> 175 prepare circleci config

- .circleci/config.yml
- checkstyle-sonar-plugin/pom.xml
- checkstyle-sonar-plugin/src/main/java/org/sonar/plugins/checkstyle/CheckstyleAuditListener.java
- checkstyle-sonar-plugin/src/main/java/org/sonar/plugins/checkstyle/CheckstyleConfiguration.java
- checkstyle-sonar-plugin/src/main/java/org/sonar/plugins/checkstyle/CheckstyleExecutor.java
- checkstyle-sonar-plugin/src/main/java/org/sonar/plugins/checkstyle/CheckstyleProfileExporter.java
- checkstyle-sonar-plugin/src/main/java/org/sonar/plugins/checkstyle/CheckstyleProfileImporter.java
- checkstyle-sonar-plugin/src/main/java/org/sonar/plugins/checkstyle/CheckstyleRulesDefinition.java
- checkstyle-sonar-plugin/src/main/java/org/sonar/plugins/checkstyle/CheckstyleSensor.java
- checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/CheckstyleAuditListenerTest.java
- checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/CheckstyleConfigurationTest.java
- checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/CheckstyleExecutorTest.java
- checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/CheckstyleProfileExporterTest.java
- checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/CheckstyleRulesDefinitionTest.java
- checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/CheckstyleSensorTest.java
- checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/internal/CheckUtil.java
- pom.xml
Issue #157. Basic changes taken from #158, then I updated dependencies of SonarQube API. I successfully tested analysis in SonarQube 7.3, 7.4 and 7.5.
(follow-up PR from #165)
> #157 add support for SQ 7.2+

- README.md
- checkstyle-sonar-plugin/src/main/resources/org/sonar/l10n/checkstyle.properties
- checkstyle-sonar-plugin/src/main/resources/org/sonar/plugins/checkstyle/rules.xml
- pom.xml
> Issue #187: update to checkstyle 8.17

- .gitignore
- checkstyle-sonar-plugin/src/main/java/org/sonar/plugins/checkstyle/CheckstyleAuditListener.java
- checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/CheckstyleAuditListenerTest.java
> Fix auto unboxing issue in CheckstyleAuditListener

- README.md
SonarCloud seems to have changed its links somehow.
> minor: fix broken SonarCloud badge

- src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle/com.puppycrawl.tools.checkstyle.checks.AvoidEscapedUnicodeCharactersCheck.html
- src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle/com.puppycrawl.tools.checkstyle.checks.annotation.PackageAnnotationCheck.html
- src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle/com.puppycrawl.tools.checkstyle.checks.design.DesignForExtensionCheck.html
- src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle/com.puppycrawl.tools.checkstyle.checks.indentation.CommentsIndentationCheck.html
- src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle/com.puppycrawl.tools.checkstyle.checks.naming.AbbreviationAsWordInNameCheck.html
- src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle/com.puppycrawl.tools.checkstyle.checks.regexp.RegexpCheck.html
- src/test/java/org/sonar/plugins/checkstyle/internal/ChecksTest.java
> Issue #225: resolve Idea vilolations on deprecated HTML tags

- .travis.yml
- config/Dockerfile
- fast-forward-merge.sh
- travis.sh
> 225 idea additional violations that IDEA show on local

- src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle/com.puppycrawl.tools.checkstyle.checks.javadoc.MissingJavadocMethodCheck.html
> Issue #229: fix TC errors

- README.md
- pom.xml
- src/main/java/org/sonar/plugins/checkstyle/CheckstyleProfileImporter.java
- src/main/resources/com/sonar/sqale/checkstyle-model.xml
- src/main/resources/org/sonar/l10n/checkstyle.properties
- src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle/com.puppycrawl.tools.checkstyle.checks.coding.MagicNumberCheck.html
- src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle/com.puppycrawl.tools.checkstyle.checks.coding.OneStatementPerLineCheck.html
- src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle/com.puppycrawl.tools.checkstyle.checks.javadoc.InvalidJavadocPositionCheck.html
- src/main/resources/org/sonar/plugins/checkstyle/rules.xml
- src/test/java/org/sonar/plugins/checkstyle/CheckstyleRulesDefinitionTest.java
fix #238 
singlesuppression enabled for line 5:
config:
> Issue #238: update to CS 8.23

- pom.xml
> Issue #248: add @muhlba91 as lead developer

- README.md
- pom.xml
- src/main/java/org/sonar/plugins/checkstyle/CheckstyleExecutor.java
- src/main/resources/org/sonar/l10n/checkstyle.properties
- src/main/resources/org/sonar/plugins/checkstyle/rules.xml
- src/test/java/org/sonar/plugins/checkstyle/CheckstyleExecutorTest.java
fixes #246 
no special updates needed as backwards compatibility is given.
> Issues #246: update to CS 8.26

- config/intellij-idea-inspections.xml
based on https://github.com/checkstyle/checkstyle/commit/3de6a350321e6f2cfb5da3a7bbf8b9912d57f0a5
https://teamcity.jetbrains.com/viewLog.html?buildId=2669084&tab=Inspection&buildTypeId=Checkstyle_SonarCheckstyleIdeaInspectionsMaster
> minor: fix teamcity violations

- pom.xml
wrap long line to be less than 100 symbols
> minor: formatting and fix url to checkstyle.org

- .ci/travis.sh
> infra: put sonar-application-7.9.2.zip to maven cache

- .ci/travis.sh
- .travis.yml
- pom.xml
- src/it/java/org/checkstyle/plugins/sonar/CheckJarTest.java
part from https://github.com/checkstyle/sonar-checkstyle/pull/258
> infra: add ITs placeholder

- .ci/travis.sh
- config/pmd-main.xml
- pom.xml
- src/it/java/org/checkstyle/plugins/sonar/RunPluginTest.java
- src/it/resources/integration-test-project/README.md
- src/it/resources/integration-test-project/pom.xml
- src/it/resources/integration-test-project/src/main/java/com/acme/App.java
- src/it/resources/integration-test-project/src/test/java/com/acme/AppTest.java
- src/test/java/org/sonar/plugins/checkstyle/CheckstyleProfileExporterTest.java
- src/test/resources/logback-test.xml
> Issue #232: migration to sonarqube 7.9 LTS

- pom.xml
- src/it/java/org/checkstyle/plugins/sonar/RunPluginTest.java
- src/test/java/org/sonar/plugins/checkstyle/CheckstyleConstantsTest.java
- src/test/java/org/sonar/plugins/checkstyle/CheckstyleSeverityUtilsTest.java
fix #274 
- update to `forbiddenapis:2.7`
- fix issues for JDK 11
> #274: update forbiddenapis

- config/intellij-idea-inspections.xml
> Issue #278: disable inspection that suggest to convert block to expression

- .travis.yml
- pom.xml
- src/it/java/org/checkstyle/plugins/sonar/RunPluginTest.java
- src/test/java/org/sonar/plugins/checkstyle/CheckstyleConstantsTest.java
- src/test/java/org/sonar/plugins/checkstyle/CheckstyleSeverityUtilsTest.java
- src/test/java/org/sonar/plugins/checkstyle/internal/ChecksTest.java
> #282 set compatibility to 1.8

- src/it/java/org/checkstyle/plugins/sonar/CheckJarTest.java
> Issue #288: match jar file name for CheckJarTest

- README.md
- pom.xml
- src/main/resources/com/sonar/sqale/checkstyle-model.xml
- src/main/resources/org/sonar/l10n/checkstyle.properties
- src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle/com.puppycrawl.tools.checkstyle.checks.coding.UnnecessarySemicolonAfterOuterTypeDeclarationCheck.html
- src/main/resources/org/sonar/plugins/checkstyle/rules.xml
- src/test/java/org/sonar/plugins/checkstyle/CheckstyleRulesDefinitionTest.java
> Issue #290: update to CS 8.31

- README.md
- pom.xml
- src/main/resources/com/sonar/sqale/checkstyle-model.xml
- src/main/resources/org/sonar/l10n/checkstyle.properties
- src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle/com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocMissingWhitespaceAfterAsteriskCheck.html
- src/main/resources/org/sonar/plugins/checkstyle/rules.xml
- src/test/java/org/sonar/plugins/checkstyle/CheckstyleRulesDefinitionTest.java
fix #292 
all new/modified check violations:
(also see https://github.com/checkstyle/checkstyle/issues/8236)
> Issue #292: update to CS 8.32

- pom.xml
resolve security alert https://github.com/checkstyle/sonar-checkstyle/network/alert/pom.xml/com.puppycrawl.tools:checkstyle/open
> dependency: upgrade checkstyle to 8.29 version

- src/main/java/org/sonar/plugins/checkstyle/metadata/CheckstyleMetadata.java
- src/test/java/org/sonar/plugins/checkstyle/metadata/CheckstyleMetadataTest.java
Fixes https://github.com/checkstyle/metadata-gen/issues/55
Screenshot:
> Issue #55(metadata-gen): fix check names

- pom.xml
- src/main/java/org/sonar/plugins/checkstyle/metadata/CheckstyleMetadata.java
Fix for https://github.com/checkstyle/sonar-checkstyle/issues/322#issuecomment-683449046
> minor: add float property type support

- src/test/java/org/sonar/plugins/checkstyle/internal/ChecksTest.java
> Issue 323: add comments in code for old metadata loading

- pom.xml
- src/main/java/org/sonar/plugins/checkstyle/metadata/CheckstyleMetadata.java
- src/test/java/org/sonar/plugins/checkstyle/CheckstyleRulesDefinitionTest.java
- src/test/java/org/sonar/plugins/checkstyle/metadata/CheckstyleMetadataTest.java
> Issue #331: fix rule template determination logic

- config/suppressions.xml
- pom.xml
- src/main/java/org/sonar/plugins/checkstyle/CheckstyleRulesDefinition.java
- src/main/java/org/sonar/plugins/checkstyle/metadata/CheckstyleMetadata.java
- src/test/java/org/sonar/plugins/checkstyle/CheckstyleRulesDefinitionTest.java
> Issue #331: add template backward compatibility

- README.md
- pom.xml
- src/test/java/org/sonar/plugins/checkstyle/CheckstyleRulesDefinitionTest.java
- wercker.yml
fix #345 
LambdaBodyLength check (2 instances configured):
testing also done as part of #338
> Issue #345: update to CS 8.37

- README.md
- pom.xml
- src/test/java/org/sonar/plugins/checkstyle/CheckstyleRulesDefinitionTest.java
> Issue #348: update to CS 8.38

- README.md
- pom.xml
- src/test/java/org/sonar/plugins/checkstyle/CheckstyleRulesDefinitionTest.java
> Issue #351: update to CS 8.39

- pom.xml
https://app.snyk.io/org/checkstyle/project/c790296d-5e05-4755-b64c-85724020c357?utm_campaign=weekly_report&utm_source=Project&fromGitHubAuth=true
the same in Github dependapbot alert.
> config: update guava to 30.0 to fix security alert

- .ci/ci.sh
- pom.xml
- src/it/java/org/checkstyle/plugins/sonar/CheckJarTest.java
- src/it/java/org/checkstyle/plugins/sonar/RunPluginTest.java
- src/main/java/org/sonar/plugins/checkstyle/CheckstylePlugin.java
- src/test/java/org/sonar/plugins/checkstyle/CheckstyleConfigurationTest.java
- src/test/java/org/sonar/plugins/checkstyle/CheckstylePluginTest.java
- src/test/java/org/sonar/plugins/checkstyle/CheckstyleProfileExporterTest.java
- test-resources/docker-compose.yml
fix #384 
plugin starting and working (tested template and non-template check):
> Issue #384: update to sonarqube 8.9 LTS

- README.md
- pom.xml
fix #375 (closes #374 as well)
template + non-template checks working:
> Issue #375: update to checkstyle 9.0.1

- README.md
- pom.xml
- test-resources/docker-compose.yml
> Issue #389: update to checkstyle 9.1

- README.md
- pom.xml
> Issue #395: update to checkstyle 9.2.1

- pom.xml
fixes #394 
based on #397 - merge afterwards!
> Issue #394: use sonar api version 8.9.0 for full 8.9.x compatibility

- README.md
- pom.xml
- src/test/java/org/sonar/plugins/checkstyle/CheckstyleRulesDefinitionTest.java
fixes #399 
`UnusedLocalVariable` check:
> Issue #399: upgrade to checkstyle 9.3

- README.md
- pom.xml
fix #411 
WhitespaceAfter LITERAL_TRY:
> Issue #411: update to Checkstyle 10.2

- README.md
- pom.xml
> Issue #414: update to Checkstyle 10.3

- .ci/bump-license-year.sh
- .github/workflows/bump-license-year.yml
> Issue #418: automate execution by Github action bump-license-year.sh

- .github/CONTRIBUTING.md
- README.md
from https://teamcity.jetbrains.com/buildConfiguration/Checkstyle_SonarCheckstyleIdeaInspectionsMaster/3897484?buildTab=Inspection
> minor: fix grammar violations from TC

- src/main/java/org/sonar/plugins/checkstyle/CheckstyleConfiguration.java
> Issue #423: remove usage of addAttribute

- README.md
- pom.xml
> Issue #417: upgrade to checkstyle 10.3.1

- README.md
- pom.xml
> Issue #426: upgrade checkstyle to 10.3.2

- src/main/java/org/sonar/plugins/checkstyle/metadata/CheckstyleMetadata.java
Removes redundant `if` statement.
> minor: Resolve redundant 'if' statement IDEA inspection

- README.md
- pom.xml
fixes #431
updates CS to 10.3.3
> Issue #431: upgrade checkstyle to 10.3.3

- src/test/java/org/sonar/plugins/checkstyle/CheckstyleConstantsTest.java
- src/test/java/org/sonar/plugins/checkstyle/CheckstyleSeverityUtilsTest.java
~I believe something is wrong with sonar's import control.~ It is legacy suppressed.
> minor: fix wrong modifier imports

- config/suppressions.xml
**Note**: may conflict with https://github.com/checkstyle/sonar-checkstyle/pull/436
> minor: remove unnecessary legacy suppressions

- .circleci/config.yml
> minor: check circle ci output

- .ci/ci.sh
- config/ant-phase-verify-sevntu.xml
- config/ant-phase-verify.xml
- config/checkstyle.properties
- config/sevntu_suppressions.xml
- pom.xml
- src/it/java/org/checkstyle/plugins/sonar/RunPluginTest.java
- src/test/java/org/sonar/plugins/checkstyle/CheckstyleRulesDefinitionTest.java
> convert maven-checkstyle-plugin to ant

- README.md
- pom.xml
> Issue #446: upgrade checkstyle to 10.4

- .gitattributes
Discussions going on at https://github.com/checkstyle/contribution/pull/717#issuecomment-1336195178
> config: add fix for line endings from main repo

- README.md
- pom.xml
> Issue #451: upgrade to checkstyle 10.5.0

- src/main/java/org/sonar/plugins/checkstyle/CheckstylePlugin.java
The API expects a list of unique scopes there.
> misc: Remove duplicate scopes
